Repository BugSwarm/bugswarm, pull requests merged in 2020-01, with the labels that each got.

#7 Added necessary missing files for Miner
  pair-classifier/pair-classifier.py
  pair-filter/dockerhub_images.json
  pair-filter/travis_images.json
Labels: bug

#10 Migrate Analyzer test framework to unittest
  tests/analyzer/tests.py
Labels: enhancement

#11 Setting up GitHub Actions
  .github/workflows/main.yml
Labels: enhancement

#12 Changed PPA for python3.6
  database/Dockerfile
Labels: bug, dependencies

#13 Fix miner and reproducer link in README
  README.md
Labels: documentation
