Repository BugSwarm/bugswarm, pull requests merged in 2020-02, with the labels that each got.

#16 Fix for standalone Analyzer entry.py
  bugswarm/analyzer/dispatcher.py
  bugswarm/analyzer/entry.py
  pair-classifier/pair-classifier.py
Labels: bug, enhancement

#18 Analyzer test fixes
  tests/analyzer/tests.py
Labels: bug

#15 Refactor Miner for additional pairs
  database/database/schema/mined_project_schema.py
  pair-filter/pair-filter.py
  pair-filter/pair_filter/utils.py
  pair-finder/pair_finder.py
  pair-finder/pair_finder/model/mined_project_builder.py
  pair-finder/pair_finder/pipeline/steps/get_jobs_from_travis_api.py
  pair-finder/pair_finder/utils.py
Labels: enhancement

#19 Added API endpoints for updating the repo in DB collections
  bugswarm/common/rest_api/database_api.py
Labels: enhancement

#20 Sync master branches between bugswarm-dev and bugswarm
  .github/workflows/sync.yml
Labels: enhancement

#17 result_comparer.py failed test comparison fix
  bugswarm/analyzer/result_comparer.py
  tests/analyzer/result_comparer/102015358-orig.log
  tests/analyzer/result_comparer/102015358-repr.log
  tests/analyzer/result_comparer/251797108-orig.log
  tests/analyzer/result_comparer/251797108-repr.log
  tests/analyzer/result_comparer/407884143-orig.log
  tests/analyzer/result_comparer/407884143-repr.log
  tests/analyzer/tests.py
Labels: bug
